openapi: 3.2.0
info:
  version: 13.1.0.0
  title: MX Open Experimental API
servers:
- url: https://127.0.0.1:8083/SecureSphere/api
tags:
- name: Experimental
paths:
  /experimental/nav/header:
    get:
      operationId: getNavigationTree
      summary: Get navigation tree
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: workspace
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/HeaderDTO'
      x-summary-source: derived
  /experimental/fam/repository-users:
    get:
      operationId: findMatchingUsers
      summary: Find matching users
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: prefix
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/FamRepositoryUsersDTO'
      x-summary-source: derived
  /experimental/fam/do-users-in-group:
    get:
      operationId: getUsersInGroup
      summary: Get users in group
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: principalId
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: fileContext
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: recordsRange
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: sorting
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/DopUsersInGroupDTO'
      x-summary-source: derived
  /experimental/fam/do-file-permissions/stat/{dataOwnerId}:
    get:
      operationId: getProgressStatistics
      summary: Get progress statistics
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: dataOwnerId
        in: path
        required: true
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/FilePermissionsStatisticsDTO'
      x-summary-source: derived
  /experimental/fam/do-file-permissions/signoff/{dataOwnerId}:
    put:
      operationId: signOffReview
      summary: Sign off review
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: dataOwnerId
        in: path
        required: true
        schema:
          type: string
        description: ''
      - name: signOffName
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        default:
          description: successful operation
      x-summary-source: derived
  /experimental/nav/ui-view-mode:
    get:
      operationId: getUIViewMode
      summary: Get UI view mode
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
      x-summary-source: derived
  /experimental/gateway/gatewayAlias:
    post:
      operationId: createAliasesForGateway
      summary: Create aliases for gateway
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        default:
          description: successful operation
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/definitions/KRPAliasDTO'
      x-summary-source: derived
  /experimental/fam/do-application-data:
    get:
      operationId: getPermissionContent
      summary: Get permission content
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/DopApplicationDataDTO'
      x-summary-source: derived
  /experimental/waf/certificateAuthorities:
    post:
      operationId: uploadCACertificate
      summary: Upload CA certificate
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        default:
          description: successful operation
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/definitions/SomMxCertificateDTO'
      x-summary-source: derived
  /experimental/nav/deployment:
    get:
      operationId: getDeployment
      summary: Get deployment
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
      x-summary-source: derived
  /experimental:
    options:
      operationId: getOptions
      summary: Get options
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        default:
          description: successful operation
      x-summary-source: derived
  /experimental/nav/workspaces:
    get:
      operationId: getWorkspaces
      summary: Get workspaces
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: workspace
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/definitions/WorkspaceDTO'
                type: array
      x-summary-source: derived
  /experimental/waf/profilePolicies/{policyName}/disableLearningEngine:
    put:
      operationId: disableProfileLearning
      summary: Disable profile learning
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: policyName
        in: path
        required: true
        schema:
          type: string
        description: ''
      responses:
        default:
          description: successful operation
      x-summary-source: derived
  /experimental/token:
    get:
      operationId: getToken
      summary: Get token
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
      x-summary-source: derived
  /experimental/fam/do-users/{dataOwnerName}:
    get:
      operationId: getAuthenticatedUser
      summary: Get authenticated user
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: dataOwnerName
        in: path
        required: true
        schema:
          type: string
        description: ''
      - name: domain
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: password
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/FamRepositoryUserDTO'
      x-summary-source: derived
  /experimental/fam/do-operation-navigation:
    post:
      operationId: getNextUnReviewedOperation
      summary: Get next un reviewed operation
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/DopOperationNavigationResponseDTO'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/definitions/DopOperationNavigationRequestDTO'
      x-summary-source: derived
  /experimental/fam/do-file-permissions/{dataOwnerId}:
    put:
      operationId: updateFilePermissions
      summary: Update file permissions
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: dataOwnerId
        in: path
        required: true
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: integer
                format: int32
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/definitions/DopUpdateOperationDTO'
      x-summary-source: derived
  /experimental/fam/do-tree-folder-obj:
    get:
      operationId: getFolderObjChildren
      summary: Get folder obj children
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: actionDoneById
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: fullPath
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: folderObj
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/TreeFolderObjsDTO'
      x-summary-source: derived
  /experimental/fam/do-file-permissions:
    get:
      operationId: getPermissionContent
      summary: Get permission content
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: actionDoneById
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: fullPathJsonStr
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: objIdJsonStr
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: fileContextJsonStr
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: filterJsonStr
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: pagingJsonStr
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: sortingJsonStr
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/FilePermissionsDTO'
      x-summary-source: derived
  /experimental/flex/checkAlarms:
    post:
      operationId: checkFlexProtectAlarms
      summary: Check flex protect alarms
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        default:
          description: successful operation
      x-summary-source: derived
  /experimental/fam/data-owner-folder/file_path_info:
    get:
      operationId: getFileObjectPathInfo
      summary: Get file object path info
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: objectId
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: fileContext
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/DopFileObjPathInfoDTO'
      x-summary-source: derived
  /experimental/fam/data-owner-folder:
    get:
      operationId: getObjectsInFolder
      summary: Get objects in folder
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      parameters:
      - name: actionDoneById
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: folderObjectId
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: fileType
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: fullPath
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: fileContext
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: filter
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: recordsRange
        in: query
        required: false
        schema:
          type: string
        description: ''
      - name: sort
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/DOFileObjectsDTO'
      x-summary-source: derived
  /experimental/fam/do-tree-folder-obj/todo:
    put:
      operationId: getNodesTodoStatus
      summary: Get nodes todo status
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/DOFolderWithUpdatedToDoDTO'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/definitions/DOFoldersToCheckTodoDTO'
      x-summary-source: derived
  /experimental/nav/about:
    get:
      operationId: getAboutInfo
      summary: Get about info
      description: ''
      tags:
      - Experimental
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/FooterDTO'
      x-summary-source: derived
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
