openapi: 3.2.0
info:
  version: 13.1.0.0
  title: MX Open Administration API
servers:
- url: https://127.0.0.1:8083/SecureSphere/api
tags:
- name: Administration
paths:
  /v1/administration/log/level:
    put:
      operationId: setLogLevel
      summary: ''
      description: ''
      tags:
      - Administration
      security:
      - basicAuth: []
      responses:
        default:
          description: successful operation
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/definitions/LogLevelDTO'
  /v1/administration/gatewayRegistrationToken:
    get:
      operationId: getGatewayRegistrationToken
      summary: ''
      description: ''
      tags:
      - Administration
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/RegistrationTokenDTO'
  /v1/administration/version:
    get:
      operationId: getVersion
      summary: ''
      description: ''
      tags:
      - Administration
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/VersionDTO'
  /v1/administration/strict:
    put:
      operationId: setStrictMode
      summary: ''
      description: ''
      tags:
      - Administration
      security:
      - basicAuth: []
      responses:
        default:
          description: successful operation
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/definitions/StrictModeDTO'
  /v1/administration/challenge:
    get:
      operationId: getChallenge
      summary: ''
      description: ''
      tags:
      - Administration
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/ChallengeDTO'
  /v1/administration/user/password/firsttime:
    post:
      operationId: getSessionId
      summary: ''
      description: ''
      tags:
      - Administration
      security:
      - basicAuth: []
      parameters:
      - name: Authorization
        in: header
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/SessionIdDTO'
  /v1/administration/flex_protect:
    post:
      operationId: uploadFlexProtectCode
      summary: ''
      description: ''
      tags:
      - Administration
      security:
      - basicAuth: []
      responses:
        default:
          description: successful operation
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/definitions/LicenseDTO'
  /v1/administration/license:
    post:
      operationId: uploadLicenseFile
      summary: ''
      description: ''
      tags:
      - Administration
      security:
      - basicAuth: []
      responses:
        default:
          description: successful operation
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/definitions/LicenseDTO'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
