openapi: 3.2.0
info:
  version: 13.1.0.0
  title: MX Open Status API
servers:
- url: https://127.0.0.1:8083/SecureSphere/api
tags:
- name: Status
paths:
  /v1/status/alarms/active:
    get:
      operationId: getDeploymentActiveAlarms
      summary: ''
      description: ''
      tags:
      - Status
      security:
      - basicAuth: []
      parameters:
      - name: deployment
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/definitions/ActiveAlarmDTO'
                type: array
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
