openapi: 3.2.0
info:
  version: 13.1.0.0
  title: MX Open Management API
servers:
- url: https://127.0.0.1:8083/SecureSphere/api
tags:
- name: Management
paths:
  /v1/management/jobs/{JobId}/currentRun:
    delete:
      operationId: abortJobById
      summary: ''
      description: ''
      tags:
      - Management
      security:
      - basicAuth: []
      parameters:
      - name: JobId
        in: path
        required: true
        schema:
          type: integer
        description: ''
      responses:
        default:
          description: successful operation
  /v1/management/jobs:
    get:
      operationId: currentlyRunningJobs
      summary: ''
      description: ''
      tags:
      - Management
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/JobsDTO'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
