openapi: 3.2.0
info:
  version: 13.1.0.0
  title: MX Open Auth API
servers:
- url: https://127.0.0.1:8083/SecureSphere/api
tags:
- name: Auth
paths:
  /v1/auth/session/roles:
    get:
      operationId: getRole
      summary: ''
      description: ''
      tags:
      - Auth
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
  /v1/auth/session:
    post:
      operationId: getSessionId
      summary: ''
      description: ''
      tags:
      - Auth
      security:
      - basicAuth: []
      parameters:
      - name: Authorization
        in: header
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/SessionIdDTO'
    delete:
      operationId: logout
      summary: ''
      description: ''
      tags:
      - Auth
      security:
      - basicAuth: []
      responses:
        default:
          description: successful operation
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
